# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme:            "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin:   "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Jekyll specific
future: true

# Site Settings
locale                   : "da"
title                    : "Vejle Idrætshøjskoles Historie"
title_separator          : "-"
name                     : "Vejle Idrætshøjskole"
description              : "Vejle Idrætshøjskoles Historie."
url                      : "" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "vih/historie" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/logo.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
# masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
staticman:
  branch                 : "master"
atom_feed:
  path                   : # blank (default) uses feed.xml


# reCaptcha
# Register your domain at https://www.google.com/recaptcha/ and choose reCAPTCHA V2
reCaptcha:
  enabled: true
  siteKey: "6LdCtVoUAAAAADcxG1WekIUuEuJy3YPoQ8DtbzK8"
  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
  # For more information, https://staticman.net/docs/encryption
  secret: "B6TmweBhBmEXsUUZKFEXOuFbAOHGBluvOCpsyTzAR+jjB5IkDNXzQo2NmMt8alWLWHh1HentKbOWAOx7HCl7AH3qgSeGWIvaTV99lKC8IakuyWGd2ZJR+eGxqN5RbmiNA1e4NXT4Z3DEMzq89iM/1VFkjSOY+LqAtWkdpJQTIGQ="


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Social Sharing
twitter:
  username               : "vihdk"
facebook:
  username               : "vihdk"
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Organization" # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/vihdk"
    - "https://www.facebook.com/vihdk"
    - "https://www.instagram.com/vihdk"

# Site search
search: true


# Analytics
analytics:
  provider               : "google-universal" # false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-4137620-10"


# Site Footer
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://twitter.com/vihdk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://www.facebook.com/vihdk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vih/historie"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/vihdk"


# Site Author
author:
  name             : "Vejle Idrætshøjskole"
  avatar           : "/assets/images/authors/vih-logo.png"# path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Grundlagt i 1942 under navnet Den Jyske Idrætsskole. Første hold starter i 1943. Fra 1998 Vejle Idrætshøjskole og fra 2007 kommer Vejle Idrætsefterskole til."
  location         : "Vejle"
  links            :
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info@vih.dk"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.vih.dk/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/vihdk"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/groups/655406751295188"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vih/historie.git"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/watch?v=Dml7gh_V7Uc&list=PLGMthFEYpLt-fp7_hhgbEbcqlnUwLEyEI"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/vihdk"


# Reading Files
include:
  - .htaccess
  - _pages
  - .well-known
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Build settings
github: [metadata]


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-include-cache


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Collections
collections:
  places:
    output: true
    permalink: /steder/:path/
  timelines:
    output: true
    permalink: /tidslinje/:path/
  songs:
    output: true
    permalink: /:collection/:path/
  faq:
    output: true
    permalink: /:collection/:path/
  persons:
    output: true
    permalink: /:collection/:path/
  yearbooks:
    output: true
    permalink: /aarsskrift/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      listen_time: false
      video_time: false
      comments: true
      share: true
      related: true
# _places
  - scope:
      path: ""
      type: places
    values:
      layout: collection-single
      author_profile: true
      listen_time: false
      video_time: false
      read_time: false
      comments: true
      share: true
      related: true
# _persons
  - scope:
      path: ""
      type: persons
    values:
      layout: collection-single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: true
      toc: true
# _timelines
  - scope:
      path: ""
      type: timelines
    values:
      layout: collection-single
      author_profile: true
      listen_time: false
      video_time: false
      read_time: false
      comments: true
      share: true
      related: true
# _songs
  - scope:
      path: ""
      type: songs
    values:
      layout: collection-single
      author_profile: true
      listen_time: false
      video_time: false
      read_time: false
      comments: true
      share: true
      related: true
# _faq
  - scope:
      path: ""
      type: faq
    values:
      layout: collection-single
      author_profile: true
      video_time: false
      listen_time: false
      read_time: true
      comments: true
      share: true
      related: true
# _yearbooks
  - scope:
      path: ""
      type: yearbooks
    values:
      layout: collection-single
      author_profile: false
      read_time: true
      listen_time: false
      video_time: false
      comments: true
      share: true
      related: true
      toc: true


# Podcast
podcast_language: "da-DK"
podcast_site_url: http://historie.vih.dk
podcast_url: http://historie.vih.dk/podcast
podcast_album_art: /assets/podcasts/cover-stemmer.png
podcast_title: Vejle Idrætshøjskoles Stemmer
podcast_owner: Vejle Idrætshøjskole
podcast_email: info@vih.dk
podcast_category: Vejle Idrætshøjskole
podcast_subcategory:
 - Historie
 - Tankegods
podcast_explicit: "no"
podcast_author: Lars Olesen
podcast_description: Stemmer fra Vejle Idrætshøjskoles historie kommer til orde.
podcast_summary: Lars Olesen, viceforstander, lader stemmerne fra Vejle Idrætshøjskole komme til orde. Vi samler på historier, viden, gode oplevelser, diskussioner fra før og nu i højskolens historie.
podcast_subtitle: Stemmer fra Vejle Idrætshøjskoles historie.  Vært er Lars Olesen.
